# App Configuration
app:
  name: smesp
  environment: ${ENVIRONMENT:local}

# Server Configuration
server:
  port: 9200
  servlet.contextPath: /api/v1/
  error.include-stacktrace: never

# Security Server Configuration
blupay:
  security:
    trusted-issuers:
      - https://hml.auth.blupay-apps.com.br/auth/realms/smesp
      - https://hml.auth.blupay-apps.com.br/auth/realms/spi-psp

# Cache Configuration
cache:
  type: redis
  null-values: false
  ttl: 300000 # 5 min
#  ttl: 600000 # 10 min
#  ttl: 86400000 # 24 hrs

# DB Configuration
db:
  addr: localhost:5432
  name: smesp
  user: smesp
  pass: smesp

# Log Level Configuration
logging:
  level:
    root: INFO

# Spring Configurations
spring:
  application:
    name: ${app.name}

  # Spring Database
  datasource:
    url: "jdbc:postgresql://${db.addr}/${db.name}"
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    username: ${db.user}
    password: ${db.pass}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate

  # Spring DB Migration
  flyway:
    enable: true
    out-of-order: true

# Doc Open Api Configuration
springdoc:
  use-fqn: true
  packagesToScan: br.com.blupay
  api-docs:
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger-ui.html

# Providers
provider:
  host:
    identity: http://localhost:9110/api/v1
  endpoint:
    people: /people
    people-credentials: /people/{personId}/credentials

encoder:
  key: rYihXjpiQQXqwwa