# App Configuration
app:
  name: smesp
  environment: ${ENVIRONMENT:local}
  config:
    min-score: 0.6

# Server Configuration
server:
  port: 9200
  servlet.contextPath: /api/v1/
  error.include-stacktrace: never

# Security Server Configuration
blupay:
  security:
    trusted-issuers:
      - https://hml.auth.blupay-apps.com.br/auth/realms/smesp
      - https://hml.auth.blupay-apps.com.br/auth/realms/spi-psp

# Cache Configuration
cache:
  type: redis
  null-values: false
  ttl: 300000 # 5 min
#  ttl: 600000 # 10 min
#  ttl: 86400000 # 24 hrs

# DB Configuration
db:
  addr: localhost:5432
  name: smesp
  user: smesp
  pass: smesp

# Log Level Configuration
logging:
  level:
    root: INFO

# Spring Configurations
spring:
  application:
    name: ${app.name}

  # Spring Database
  datasource:
    url: "jdbc:postgresql://${db.addr}/${db.name}"
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    username: ${db.user}
    password: ${db.pass}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate

  # Spring DB Migration
  flyway:
    enable: true
    out-of-order: true

# Doc Open Api Configuration
springdoc:
  use-fqn: true
  packagesToScan: br.com.blupay
  api-docs:
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger-ui.html

service:
  token:
    type: BRL

# Providers
provider:
  token:
    host: https://blupay-tk.com.br/api/token
#    host: http://localhost:6901/api/token
    endpoint:
      node:
        public-key: /node/public-key
        party: /node/party
      wallet:
        get: /wallet/get
        balance: /wallet/balance
        ioy-balance: /wallet/ioy-balance
        settlement-balance: /wallet/settlement-balance
        issue: /wallet
        add-role: /wallet/role
      token:
        issue: /token/issue
        move: /token/move
        redeem: /token/redeem
        safe-move: /token/safe-move
        pay-ioy: /token/pay-ioy
        settlement-order: /token/settlement-order
  identity:
    host: http://localhost:9110/api/v1
    endpoint:
      people:
        root: /people
        credentials: /people/{personId}/credentials
      validations:
        root: /validations
        verify-rules: /validations/verify-rules

encoder:
  key: rYihXjpiQQXqwwa